import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "bg-primary": "#F8FAFC",
        "bg-secondary": "#F1F5F9",
        surface: "#FFFFFF",
        "surface-elevated": "#FFFFFF",
        border: "#E2E8F0",
        "border-hover": "rgba(6, 182, 212, 0.15)",
        accent: "#06B6D4",
        "accent-hover": "#0891B2",
        "accent-glow": "rgba(6, 182, 212, 0.08)",
        success: "#10B981",
        warning: "#F59E0B",
        danger: "#EF4444",
        "text-primary": "#0F172A",
        "text-secondary": "#475569",
        "text-muted": "#64748B",
        "org-isro": "#A0784C",
        "org-intel": "#5B7DB1",
        "org-tifr": "#8B6CB4",
        "org-tata": "#4A8C6F",
        "org-drdo": "#B85450",

        background: "#F8FAFC",
        foreground: "#0F172A",
        card: "#FFFFFF",
        "card-foreground": "#0F172A",
        popover: "#FFFFFF",
        "popover-foreground": "#0F172A",
        primary: "#06B6D4",
        "primary-foreground": "#FFFFFF",
        secondary: "#F1F5F9",
        "secondary-foreground": "#0F172A",
        muted: "#E2E8F0",
        "muted-foreground": "#64748B",
        "accent-foreground": "#FFFFFF",
        destructive: "#EF4444",
        "destructive-foreground": "#FFFFFF",
        input: "#FFFFFF",
        ring: "#06B6D4",
        navy: "#F8FAFC",
        "navy-light": "#F1F5F9",
        cyan: "#06B6D4",
      },
      fontFamily: {
        display: ["var(--font-space-grotesk)", "sans-serif"],
        body: ["var(--font-inter)", "sans-serif"],
        mono: ["Geist Mono", "monospace"],
      },
      fontSize: {
        xxs: "0.625rem",
      },
      borderRadius: {
        sm: "6px",
        md: "8px",
        lg: "12px",
        xl: "16px",
        "2xl": "24px",
        full: "9999px",
        card: "12px",
        pill: "9999px",
      },
      boxShadow: {
        card: "0 1px 2px rgba(0,0,0,0.3)",
        "card-hover": "0 0 24px rgba(34, 211, 238, 0.08)",
        "glow-cyan": "0 0 24px rgba(34, 211, 238, 0.15)",
        "glow-sm": "0 0 20px rgba(34, 211, 238, 0.06)",
        "card-dark": "0 4px 24px rgba(0, 0, 0, 0.3)",
        "glow-btn": "0 0 24px rgba(34, 211, 238, 0.2)",
      },
      backgroundImage: {
        "gradient-hero": "linear-gradient(to right, #22D3EE, #3B82F6)",
        "gradient-deadline": "linear-gradient(to right, #F59E0B, #EF4444)",
        "gradient-card-border": "linear-gradient(to right, transparent, rgba(34, 211, 238, 0.2), transparent)",
        "gradient-radial-cyan": "radial-gradient(ellipse at center, rgba(34, 211, 238, 0.05) 0%, transparent 70%)",
      },
    },
  },
  plugins: [require("@tailwindcss/typography")],
};
export default config;
