import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "#0B1120",
        foreground: "#FFFFFF",
        card: "#1A2438",
        "card-foreground": "#FFFFFF",
        popover: "#111827",
        "popover-foreground": "#FFFFFF",
        "text-primary": "#F9FAFB",
        "text-muted": "#94A3B8",
        primary: "#00E5FF",
        "primary-foreground": "#0B1120",
        secondary: "#111827",
        "secondary-foreground": "#FFFFFF",
        muted: "#1F2937",
        "muted-foreground": "#94A3B8",
        accent: "#3B82F6",
        "accent-foreground": "#FFFFFF",
        destructive: "#EF4444",
        "destructive-foreground": "#FFFFFF",
        success: "#10B981",
        warning: "#F59E0B",
        danger: "#EF4444",
        border: "#1F2937",
        input: "#111827",
        "input-background": "#1A2438",
        "switch-background": "#1F2937",
        ring: "#00E5FF",
        "chart-1": "#00E5FF",
        "chart-2": "#3B82F6",
        "chart-3": "#10B981",
        "chart-4": "#F59E0B",
        "chart-5": "#8B5CF6",
        sidebar: "#111827",
        "sidebar-foreground": "#FFFFFF",
        "sidebar-primary": "#00E5FF",
        "sidebar-primary-foreground": "#0B1120",
        "sidebar-accent": "#1A2438",
        "sidebar-accent-foreground": "#FFFFFF",
        "sidebar-border": "#1F2937",
        "sidebar-ring": "#00E5FF",
        navy: "#0B1120",
        "navy-light": "#1A2438",
        cyan: "#00E5FF",
      },
      fontFamily: {
        display: ["Space Grotesk", "sans-serif"],
        body: ["Inter", "sans-serif"],
        mono: ["Geist Mono", "monospace"],
      },
      fontSize: {
        xxs: "0.625rem",
      },
      borderRadius: {
        "2xl": "1rem",
        "3xl": "1.5rem",
      },
      boxShadow: {
        card: "0 0 24px rgba(0, 229, 255, 0.08)",
        "card-hover": "0 0 24px rgba(0, 229, 255, 0.12)",
        "glow-cyan": "0 0 32px rgba(0, 229, 255, 0.25)",
        "glow-sm": "0 0 20px rgba(0, 229, 255, 0.06)",
        "card-dark": "0 4px 24px rgba(0, 0, 0, 0.3)",
        "glow-btn": "0 0 24px rgba(0, 229, 255, 0.2)",
      },
      backgroundImage: {
        "gradient-hero": "linear-gradient(to right, #00E5FF, #3B82F6)",
        "gradient-deadline": "linear-gradient(to right, #F59E0B, #EF4444)",
        "gradient-card-border": "linear-gradient(to right, transparent, rgba(0, 229, 255, 0.2), transparent)",
        "gradient-radial-cyan": "radial-gradient(ellipse at center, rgba(0, 229, 255, 0.05) 0%, transparent 70%)",
      },
    },
  },
  plugins: [require("@tailwindcss/typography")],
};
export default config;
